on:
  push:
    branches:
      - main
name: ðŸš€ Deploy Bohol Island Tours website on push
jobs:
  web-deploy:
    name: ðŸŽ‰ Deploy Bohol Island Tours Livesite Server
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
    - name: ðŸšš Get latest code
      uses: actions/checkout@v2
    
    - name: ðŸ“‚ Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: www1.boholislandtours.com
        username: ${{ secrets.ftp_username }}
        password: ${{ secrets.ftp_password }}
        server-dir: /
        exclude: |
          **/application/cache/**
          **/application/config/database.php
          **/.buildpath/**
          .ftp-deploy-sync-state.json
          .git-ftp.log
          .htaccess
          .project